### ISSUE TITLE
100% cpu for projects with symlink loops

### ISSUE THREAD

**Issue by tomas-abrahamsson** [kjellwinblad/yaemep#3]
The setup was a (large and old) project that contains symlink loops, like this:
```
$ ls -l some/dir/
...  some-sub-dir -> ../..
...
```
This caused the `emacs_erlang_yaemep_support.erl` helper to go into infinite loop and consume 100% cpu for the `update_etags_project_dir` and `update_completion_cache` commands.
I investigated the `update_etags_project_dir` a bit, and it is actually the call to `filelib:wildcard(filename:join(Directory, SearchPattern))` in `update_etags/4` that never returns, traversing `.../some/dir/some-sub-dir/some/dir/some-sub-dir/some/dir/some-sub-dir/...` indefinitely. I found this using `strace -e trace=file -ff -p <pid-of-beam-consuming-cpu>`.

Maybe this is a problem for `fileilb:wildcard/1,2` rather than for yaemep, but on the other hand, the file pattern it uses in this case, `**/*.{erl,hrl}` is so simple it would be possible to work around the `filelib:wildcard/1` loop. I took brief look at using `filelib:fold_files/5` instead, but it seems to follow symlinks indefinitely too, which leads me to think it would be necessary to write some file traversal code of ones own. Do you have any opinion about this?

(Why the project contains symlink loops? Can they be removed? It is a large project containing not only Erlang code, that has been around for some time. It has even survived a change of version control system, and I think some of the symlink loops may have been adaptations to get some tools to work correctly. In this particular case, removal of symlinks causing loops would not be an option, but it would still be good to be able to use yaemep.)

**Comment by kjellwinblad** [comment]
Thanks for reporting this issue. At least it does not seem like a very useful behavior that `fileilb:wildcard` goes into an infinite loop when there are symlink loops so I think it would be good to report this as a bug in the [Erlang issue tracker](https://bugs.erlang.org). @tomas-abrahamsson can you file such a bug? 

> Do you have any opinion about this?

I agree that it would be nice to have a work around for this issue that at least covers the common case with the file pattern `**/*.{erl,hrl}` . One could also use a simple regular expression to make a work around cover file patterns of the form `**/*.{ext1,ext2,ext3,...,extN}`. One idea I have is to wrap the `fileilb:wildcard` call inside a separate process and only use the workaround if the `filelib:wildcard`-runner has not completed within a fixeed amount of time, but I'm not sure if that will be worth the extra effort and added complexity. I would be happy to accept a pull-request with a good workaround. Please let me know if you have any additional questions or anything you want to discuss.  

Note that the `filelib:wildcard` function is used in several places in `emacs_erlang_yaemep_support.erl` not only used in `update_etags`.  A work around would need to update all places where `filelib:wildcard` are used.

**Comment by tomas-abrahamsson** [comment]
I had forgotten about the `ELOOP` error.
```
$ mkdir /tmp/symlink-loops
$ cd /tmp/symlink-loops
$ ln -s . l
$ touch x.txt
$ ls /tmp/symlink-loops/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/x.txt  
/tmp/symlink-loops/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/x.txt
$ ls /tmp/symlink-loops/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/x.txt 
ls: cannot access '/tmp/symlink-loops/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/l/x.txt': Too many levels of symbolic links
```
So the cpu consumed is indeed finite. (will try to change the title of this ticket.) But if the directory tree is large and a symlink points back many levels towards the root, the time can be very long, which is what happened in our use-case. The escript helper had consumed several gigabytes of memory after many hours and was still running when I killed it.

Given `eloop`, whether it is still a bug in `filelib:wildcard`, I'm not so sure any more, but I'll try to make a PR for yaemep anyway. I've been considering whether to follow symlinks to outside the project directory tree, and a possible valid use-case could be if some files are under git annex or git lfs in conjuction with multiple git worktrees: [_Like Git LFS, git-annex takes large files out of Git's history. The way it handles this is by storing a symbolic link to the file in `.git/annex.`_](https://lwn.net/Articles/774125/) Maybe this case is not too common, but on the other hand there may be non-git use-cases too.

I, too, think it is wise to avoid a timeout for `filelib:wildcard`, with a fallback, mostly because what is a suitable timeout? Even if there are no symlink loops, it can still take long for a large project on a slow nfs disk.

**Comment by kjellwinblad** [comment]
>  I've been considering whether to follow symlinks to outside the project directory tree, and a possible valid use-case could be if some files are under git annex or git lfs in conjuction with multiple git worktrees...

I think it should be possible to avoid loops and still follow symlinks by keeping a set of already visited folders (to avoid visiting the same folder twice) while searching the file system. The 'file:read_link_info/1' and `file:read_link/1` functions can be used to check if something is a symlink and what folder the symlink is pointing to. @tomas-abrahamsson  Do you see any problems with this approach?

**Comment by tomas-abrahamsson** [comment]
Yes, that should be doable.

**Comment by kjellwinblad** [comment]
Closing as this has been fixed (see https://github.com/kjellwinblad/yaemep/pull/4)
